# Generated by Django 4.2.10 on 2024-02-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='networkadmin',
            table='NetworkAdmin',
        ),
        migrations.AlterModelTable(
            name='router',
            table='Router',
        ),
    ]
